.TH MUSW 1
.SH NAME
musw, muswd \- multi-user spacewar!
.SH SYNOPSIS
.B games/musw
[
.B -dg
]
.I dialstring
.br
.B games/muswd
[
.B -d
]
[
.B -a
.I addr
]
.SH DESCRIPTION
.I Musw
is a multi-user, on-line version of
.IR Spacewar! ,
the space dogfight simulation game developed by Steve Russell in the 1960s for the PDP-1.
.SH EXAMPLE
.SH SOURCE
.B /sys/src/games/musw
.SH SEE ALSO
.IR vmodeled (1)
.br
https://www.masswerk.at/spacewar/
.br
https://www.masswerk.at/spacewar/SpacewarOrigin.html
.SH BUGS
.SH HISTORY
